//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ogr_ID { get; set; }
        public string ogr_Name { get; set; }
        public string ogr_Surname { get; set; }
        public Nullable<int> ogr_Bolum_ID { get; set; }
        public string ogr_Tc { get; set; }
        public Nullable<int> ogr_Kan_Grubu_ID { get; set; }
        public string ogr_Dogum_Tarihi { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Kan_Grubu_Bilgi Kan_Grubu_Bilgi { get; set; }
    }
}
